version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
clone_folder: c:\indi-omnia
environment:
  QTDIR: C:\Qt\5.9.2\msvc2015_64
  PATH: '%PATH%;%QTDIR%\bin;C:\MinGW\bin'
before_build:
- cmd: >-
    cd c:\indi-omnia

    mkdir build && cd build

    cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: c:\indi-omnia\build\INSTALL.vcxproj
  parallel: true
  verbosity: minimal
after_build:
    cpack -C Release

test_script:
- cmd: ctest --output-on-failure

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: PpGyQ04Yi/c106VzEpX6jVoeRtQfCYq98S5cawPdamvVdwhFHO1HghDKl9BQxMpJLNt4gsEbi5K+6ooRdZgFbYVy00P88k4CwzlriUYvE6j3aJBoGCRSz5NUKOZKYFvjn8+a1ACL9ZjOdCS4Koqc9cSG/4+NI/paENS5eDZgWumlBFL+GyoZK5QNm0uXUVlfy2s8mNMbiQ6UPYwYDVcCJIO9/ItwrL7VLlhOesOnDoGSnBJqpl7TCEAmx4Y/r/YReBE25wIKgmJMb2QHBKcoVyYJ4oVJfuGcq+42YN7KeEKI+zScQfCQR+AvNfr6r+7xQCVaKZk4Otej0QfarqdLSK4Q5gLNCSS8uSLM8eKx7v8qiiTkDwCgOB+OPcmI5MOkUYE1iNOVyEZjREgnP/5hTCKx2PSEad1SBrITNL2uM3CwQrzkHluud05m//zz0ftaGduQmZXdiK4Ux2LdtEtflfS/KXH2bYU2Ok/Uc0UJSbLBsNPaJIc7Q5kSEOoE5jWGhDk8Gq2T28L4uupoXzsV1CX/Kd+/bf0wh7KlQBDk1H0JkLtaEpokty31r8+56TgnEJxdgAjoqVNBKwHxFRREjpdyfX7CFiRFaThyYT454/HHxZf1C/ZmCxG2AmWTWoxOytieVW3MAmWCZOOQ5AMmjZ9NNNYhjNA0wrLZaTstU0c=
  artifact: indi-omnia-*            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only


