version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
clone_folder: c:\indi-omnia
environment:
  QTDIR: C:\Qt\5.9.2\msvc2015_64
  PATH: '%PATH%;%QTDIR%\bin;C:\MinGW\bin'
before_build:
- cmd: >-
    cd c:\indi-omnia

    mkdir build && cd build

    cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: c:\indi-omnia\build\INSTALL.vcxproj
  parallel: true
  verbosity: minimal
after_build:
    ctest --output-on-failure

    cpack -C Release

deploy:
  provider: GitHub
  auth_token:
    secure: ANohpQYwjELgG3tdPa2eTbM/OVsEl6HAnqU5kK/ZrXn+qsk3AE1gUm2qaUGLMqRE
  artifact: /indiomnia\\build\\indiomnia-.*/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only

after_deploy:
  dir




