version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
clone_folder: c:\indi-omnia
environment:
  QTDIR: C:\Qt\5.9.2\msvc2015_64
  PATH: '%PATH%;%QTDIR%\bin;C:\MinGW\bin'
before_build:
- cmd: >-
    cd c:\indi-omnia
    mkdir build && cd build
    cmake -G "Visual Studio 14 2015 Win64" ..
build:
  project: c:\indi-omnia\build\INSTALL.vcxproj
  parallel: true
  verbosity: minimal
test_script:
- cmd: ctest --output-on-failure

