language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc
  - sudo apt-get -qq install g++
  - sudo apt-get -qq install qt59quickcontrols2
  - sudo apt-get -qq install ninja-build

install:

before_script:
  - source /opt/qt59/bin/qt59-env.sh
  - mkdir build
  - cd build

script:
  - cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"
  - ninja
  - ninja install
  - ctest --output-on-failure
  - cpack

notifications:
  email:
    - asiniscalchi@gmail.com

