language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang

addons:
  apt:
    packages:
      - graphviz

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty; fi;
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi;
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq install qt59quickcontrols2; fi;
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq install ninja-build; fi;

install:

before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then source /opt/qt59/bin/qt59-env.sh; fi;
  - mkdir build
  - cd build

script:
  - cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"
  - ninja
  - ctest --output-on-failure
  - cpack

notifications:
  email:
    - asiniscalchi@gmail.com

